dist: xenial

language: node_js

node_js:
  - 10
  - 12

cache: npm

env:
  - SEQUELIZE=^3.0.0
  - SEQUELIZE=^4.0.0

before_script:
  - npm i sequelize@$(echo $SEQUELIZE)
  - npm run prepare

script:
  - npm run lint
  - npm test
